version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.8.10
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python -m unittest discover -s test/unittest/ -p "test*.py"